### ISSUE TITLE
OpenGL backend?

### ISSUE THREAD

**Issue by mcourteaux** [nyorain/rvg#3]
I'm looking for an Vulkan compatible alternative to NanoVG. As you said the NanoVG interface is not a good fit to the Vulkan design, I'm wondering: would your rvg be suitable to build a OpenGL backend for it?

Essentially, I like NanoVG a lot, but I want to be ready for the future with Vulkan. On the other hand, I don't want to drop OpenGL immediately as well, for compatibility.

**Comment by nyorain** [comment]
Well, the current implementation does not abstract over rendering apis - to keep things as simple and performant as possible it uses vulkan directly. With a new layer of abstraction it would probably possible to do this but not really in the intended scope of the library since this complicates things a lot (and it would need a major rewrite, notice how vulkan primitives like semaphores for synchronization or command buffers for recording/rendering are used all over the library and opengl handles some of these things in a completely different way).

**Comment by nyorain** [comment]
Closing this as wontfix.
